Basic Stats-2

Problem Statment: Hospital patient

1.	Load the patient dataset and show summary with info().

In [109]:
import pandas as pd
import seaborn as sns

In [111]:
patients=pd.read_csv('Patient_Data.csv')
patients

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [113]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [115]:
billing=pd.read_csv('Billing_Data.csv')
billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [117]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [119]:
selected_columns_billing=patients[['PatientID', 'Department', 'Doctor', 'BillAmount']]
selected_columns_billing

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [121]:
patients_drop=patients.drop(columns=['ReceptionistID'])
patients_drop

   PatientID     Name   Department     Doctor  BillAmount       CheckInTime
0        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00
1        102      Bob    Neurology   Dr. John         NaN  2023-01-11 10:30
2        103  Charlie  Orthopedics    Dr. Lee      7500.0  2023-01-12 11:00
3        104    David   Cardiology  Dr. Smith      6200.0  2023-01-13 12:00
4        105      Eva  Dermatology   Dr. Rose         NaN  2023-01-14 08:45
5        101    Alice   Cardiology  Dr. Smith      5000.0  2023-01-10 09:00

In [123]:
patients_drop=patients.drop(columns=['CheckInTime'])
patients_drop

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2
5        101    Alice   Cardiology  Dr. Smith      5000.0               1

Use groupby to find total bill amount per department.

In [125]:
total_bill_per_department=selected_columns_billing.groupby('Department')['BillAmount'].sum().reset_index()
total_bill_per_department

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

Use groupby to find total bill amount per department.

In [127]:
Remove_dup_patient=patients.drop_duplicates("PatientID")
Remove_dup_patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

Fill missing BillAmount values with the mean bill amount.

In [129]:
bill_amount=patients['BillAmount'].mean()
patients['BillAmount'] = patients['BillAmount'].fillna(bill_amount)
patients

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

Merge the billing dataset with patient dataset on PatientID

In [131]:
marge_patients=pd.merge(patients,selected_columns_billing,on='PatientID')
marge_patients

,PatientID,Name,Department_x,Doctor_x,BillAmount_x,ReceptionistID,CheckInTime,Department_y,Doctor_y,BillAmount_y
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0
1,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0
2,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,Neurology,Dr. John,NaN
3,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,Orthopedics,Dr. Lee,7500.0
4,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,Cardiology,Dr. Smith,6200.0
5,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,Dermatology,Dr. Rose,NaN
6,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0
7,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0

Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [133]:
new_billing_columns=pd.DataFrame({
    'InsuranceCovered': [4000, 2000, 3500],  
    'FinalAmount': [1000, 1000, 500] 
})
new_billing_columns

   InsuranceCovered  FinalAmount
0              4000         1000
1              2000         1000
2              3500          500

Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [135]:
concat_columns=pd.concat([marge_patients,new_billing_columns],axis=1)
concat_columns

,PatientID,Name,Department_x,Doctor_x,BillAmount_x,ReceptionistID,CheckInTime,Department_y,Doctor_y,BillAmount_y,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0,4000.0,1000.0
1,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0,2000.0,1000.0
2,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,Neurology,Dr. John,NaN,3500.0,500.0
3,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,Orthopedics,Dr. Lee,7500.0,NaN,NaN
4,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,Cardiology,Dr. Smith,6200.0,NaN,NaN
5,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,Dermatology,Dr. Rose,NaN,NaN,NaN
6,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0,NaN,NaN
7,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,Cardiology,Dr. Smith,5000.0,NaN,NaN

In [137]:
marge_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       8 non-null      int64
 1   Name            8 non-null      object
 2   Department_x    8 non-null      object
 3   Doctor_x        8 non-null      object
 4   BillAmount_x    8 non-null      float64
 5   ReceptionistID  8 non-null      int64
 6   CheckInTime     8 non-null      object
 7   Department_y    8 non-null      object
 8   Doctor_y        8 non-null      object
 9   BillAmount_y    6 non-null      float64
dtypes: float64(2), int64(2), object(6)
memory usage: 772.0+ bytes