### ARTIFICIAL NEURAL NETWORKS

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("sonardataset.csv")

In [3]:
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [5]:
df.columns

Index(['x_1', 'x_2', 'x_3', 'x_4', 'x_5', 'x_6', 'x_7', 'x_8', 'x_9', 'x_10',
       'x_11', 'x_12', 'x_13', 'x_14', 'x_15', 'x_16', 'x_17', 'x_18', 'x_19',
       'x_20', 'x_21', 'x_22', 'x_23', 'x_24', 'x_25', 'x_26', 'x_27', 'x_28',
       'x_29', 'x_30', 'x_31', 'x_32', 'x_33', 'x_34', 'x_35', 'x_36', 'x_37',
       'x_38', 'x_39', 'x_40', 'x_41', 'x_42', 'x_43', 'x_44', 'x_45', 'x_46',
       'x_47', 'x_48', 'x_49', 'x_50', 'x_51', 'x_52', 'x_53', 'x_54', 'x_55',
       'x_56', 'x_57', 'x_58', 'x_59', 'x_60', 'Y'],
      dtype='object')

In [6]:
df.shape

(208, 61)

In [7]:
df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [8]:
df.isnull().sum()

x_1     0
x_2     0
x_3     0
x_4     0
x_5     0
       ..
x_57    0
x_58    0
x_59    0
x_60    0
Y       0
Length: 61, dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
#Class Distribution
print(df['Y'].value_counts())

Y
M    111
R     97
Name: count, dtype: int64

In [11]:
#Separate Features and Target
X = df.iloc[:,0:60]
y = df.iloc[:,60]

In [12]:
#Encode Target Variable
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(y[:10])

[1 1 1 1 1 1 1 1 1 1]

In [13]:
# Split Dataset
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split( X, y ,test_size=0.20, random_state=42, stratify=y)

In [14]:
#Normalize Data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [15]:
#Build ANN Model (Sequential Model)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(60,)))

model.add(Dense(32, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

C:\Users\komal\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
# Compile Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │           3,904 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,017 (23.50 KB)

 Trainable params: 6,017 (23.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
#Train Model

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.4773 - loss: 0.8731 - val_accuracy: 0.7059 - val_loss: 0.7462
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6136 - loss: 0.6417 - val_accuracy: 0.6471 - val_loss: 0.6447
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7576 - loss: 0.5384 - val_accuracy: 0.6765 - val_loss: 0.5934
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7879 - loss: 0.4825 - val_accuracy: 0.7647 - val_loss: 0.5366
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8712 - loss: 0.4310 - val_accuracy: 0.7941 - val_loss: 0.4795
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8939 - loss: 0.3912 - val_accuracy: 0.7941 - val_loss: 0.4410
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3514 - val_accuracy: 0.8529 - val_loss: 0.4268
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9318 - loss: 0.3177 - val_accuracy: 0.8529 - val_loss: 0.4125
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9394 - loss: 0.2865 - val_accuracy: 0.8529 - val_loss: 0.3901
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9470 - loss: 0.2591 - val_accuracy: 0.8529 - val_loss: 0.3856
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9470 - loss: 0.2328 - val_accuracy: 0.8529 - val_loss: 0.3673
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9621 - loss: 0.2105 - val_accuracy: 0.8529 - val_loss: 0.3521
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1898 - val_accuracy: 0.8529 - val_loss: 0.3496
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9621 - loss: 0.1717 - val_accuracy: 0.8529 - val_loss: 0.3476
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9773 - loss: 0.1555 - val_accuracy: 0.8529 - val_loss: 0.3379
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.1394 - val_accuracy: 0.8529 - val_loss: 0.3325
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9924 - loss: 0.1245 - val_accuracy: 0.8529 - val_loss: 0.3274
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.1123 - val_accuracy: 0.8529 - val_loss: 0.3270
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.1013 - val_accuracy: 0.8529 - val_loss: 0.3283
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0909 - val_accuracy: 0.8529 - val_loss: 0.3341
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0813 - val_accuracy: 0.8824 - val_loss: 0.3467
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0728 - val_accuracy: 0.8824 - val_loss: 0.3516
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0658 - val_accuracy: 0.8824 - val_loss: 0.3571
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0593 - val_accuracy: 0.8824 - val_loss: 0.3647
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0526 - val_accuracy: 0.8824 - val_loss: 0.3627
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0478 - val_accuracy: 0.8824 - val_loss: 0.3619
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0433 - val_accuracy: 0.8824 - val_loss: 0.3696
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0393 - val_accuracy: 0.8824 - val_loss: 0.3836
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0351 - val_accuracy: 0.8824 - val_loss: 0.3905
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0319 - val_accuracy: 0.8824 - val_loss: 0.3951
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0289 - val_accuracy: 0.8824 - val_loss: 0.4009
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0262 - val_accuracy: 0.8824 - val_loss: 0.4067
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0239 - val_accuracy: 0.8824 - val_loss: 0.4154
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0219 - val_accuracy: 0.8824 - val_loss: 0.4254
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0202 - val_accuracy: 0.8824 - val_loss: 0.4313
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0184 - val_accuracy: 0.8824 - val_loss: 0.4359
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0172 - val_accuracy: 0.8824 - val_loss: 0.4432
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0156 - val_accuracy: 0.8824 - val_loss: 0.4538
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0145 - val_accuracy: 0.8824 - val_loss: 0.4645
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0133 - val_accuracy: 0.8824 - val_loss: 0.4696
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 0.8824 - val_loss: 0.4747
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0114 - val_accuracy: 0.8824 - val_loss: 0.4763
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0108 - val_accuracy: 0.8824 - val_loss: 0.4773
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0101 - val_accuracy: 0.8824 - val_loss: 0.4877
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0093 - val_accuracy: 0.8824 - val_loss: 0.4967
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0087 - val_accuracy: 0.8824 - val_loss: 0.5017
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0081 - val_accuracy: 0.8824 - val_loss: 0.5058
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.8824 - val_loss: 0.5058
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0072 - val_accuracy: 0.8824 - val_loss: 0.5077
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.8824 - val_loss: 0.5112
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.8824 - val_loss: 0.5169
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.8824 - val_loss: 0.5186
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.8824 - val_loss: 0.5223
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8824 - val_loss: 0.5272
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.8824 - val_loss: 0.5294
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.8824 - val_loss: 0.5342
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.8824 - val_loss: 0.5389
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.8824 - val_loss: 0.5426
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.8824 - val_loss: 0.5462
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.8824 - val_loss: 0.5507
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.8824 - val_loss: 0.5571
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.8824 - val_loss: 0.5624
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.8824 - val_loss: 0.5661
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.8824 - val_loss: 0.5673
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.8824 - val_loss: 0.5693
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.8824 - val_loss: 0.5722
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.8824 - val_loss: 0.5752
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.8824 - val_loss: 0.5792
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.8824 - val_loss: 0.5815
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.8824 - val_loss: 0.5827
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.8824 - val_loss: 0.5857
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.8824 - val_loss: 0.5872
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.8824 - val_loss: 0.5903
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.8824 - val_loss: 0.5926
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8824 - val_loss: 0.5940
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8824 - val_loss: 0.5967
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.8824 - val_loss: 0.5995
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.8824 - val_loss: 0.5980
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.8824 - val_loss: 0.6009
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8824 - val_loss: 0.6044
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8824 - val_loss: 0.6088
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8824 - val_loss: 0.6126
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.8824 - val_loss: 0.6148
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.8824 - val_loss: 0.6161
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8824 - val_loss: 0.6188
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8824 - val_loss: 0.6218
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8824 - val_loss: 0.6248
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8824 - val_loss: 0.6271
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8824 - val_loss: 0.6290
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8824 - val_loss: 0.6301
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8824 - val_loss: 0.6316
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.8824 - val_loss: 0.6343
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.8824 - val_loss: 0.6368
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.8824 - val_loss: 0.6382
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.6394
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.6413
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.6434
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.6453
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.6490
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.6514

In [19]:
#Predict Test Data 
y_pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

In [20]:
# Convert Probabilities into Classes
y_pred = (y_pred > 0.5).astype(int)

In [21]:
#Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)

print("Precision :", precision)

print("Recall :", recall)

print("F1 Score :", f1)

Accuracy : 0.8571428571428571
Precision : 0.9375
Recall : 0.75
F1 Score : 0.8333333333333334

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.95      0.88        22
           1       0.94      0.75      0.83        20

    accuracy                           0.86        42
   macro avg       0.87      0.85      0.85        42
weighted avg       0.87      0.86      0.86        42

In [23]:
#Hyperparameter Tuning using Keras Tuner
def build_model(hp):

    model = Sequential()

    model.add(
        Dense(
            units=hp.Int(
                'units_input',
                min_value=32,
                max_value=128,
                step=32
            ),
            activation=hp.Choice(
                'activation',
                ['relu','tanh']
            ),
            input_shape=(60,)
        )
    )

    for i in range(
        hp.Int(
            'hidden_layers',
            1,
            3
        )
    ):

        model.add(
            Dense(
                units=hp.Int(
                    f'units_{i}',
                    min_value=16,
                    max_value=128,
                    step=16
                ),
                activation=hp.Choice(
                    'activation',
                    ['relu','tanh']
                )
            )
        )

    model.add(Dense(1, activation='sigmoid'))

    lr = hp.Choice(
        'learning_rate',
        [0.01,0.001,0.0001]
    )

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [24]:
!pip install keras-tuner

Requirement already satisfied: keras-tuner in c:\users\komal\anaconda3\lib\site-packages (1.4.8)
Requirement already satisfied: keras in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (3.14.0)
Requirement already satisfied: packaging in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (2.32.5)
Requirement already satisfied: kt-legacy in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in c:\users\komal\anaconda3\lib\site-packages (from keras-tuner) (6.33.6)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\komal\anaconda3\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (2.4.0)
Requirement already satisfied: numpy in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (2.3.5)
Requirement already satisfied: rich in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (14.2.0)
Requirement already satisfied: namex in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in c:\users\komal\anaconda3\lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\komal\anaconda3\lib\site-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\komal\anaconda3\lib\site-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\komal\anaconda3\lib\site-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\komal\anaconda3\lib\site-packages (from requests->keras-tuner) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\komal\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\komal\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\komal\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [25]:
!pip install tensorboard

Requirement already satisfied: tensorboard in c:\users\komal\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (2.3.5)
Requirement already satisfied: packaging in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (6.33.6)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (80.9.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\komal\anaconda3\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\komal\anaconda3\lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\komal\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)

In [26]:
#Create Tuner
import keras_tuner as kt
from tensorflow.keras.optimizers import Adam

tuner = kt.RandomSearch(

    build_model,

    objective='val_accuracy',

    max_trials=10,

    overwrite=True,

    directory='ANN_Tuning',

    project_name='Sonar'
)

C:\Users\komal\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [27]:
#Start Search
tuner.search(

    X_train,

    y_train,

    epochs=50,

    validation_split=0.2,

    verbose=1
)

Trial 10 Complete [00h 00m 10s]
val_accuracy: 0.8823529481887817

Best val_accuracy So Far: 0.9411764740943909
Total elapsed time: 00h 01m 42s

In [28]:
#Best Hyperparameters
best_hp = tuner.get_best_hyperparameters(1)[0]

print(best_hp.values)

{'units_input': 128, 'activation': 'tanh', 'hidden_layers': 3, 'units_0': 32, 'learning_rate': 0.01, 'units_1': 16, 'units_2': 96}

In [29]:
#Build Best Model
best_model = tuner.hypermodel.build(best_hp)

In [30]:
#Train Best Model
best_model.fit(

    X_train,

    y_train,

    epochs=100,

    batch_size=16,

    validation_split=0.2,

    verbose=1
)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.6212 - loss: 0.5855 - val_accuracy: 0.8824 - val_loss: 0.3158
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8182 - loss: 0.3720 - val_accuracy: 0.8824 - val_loss: 0.3973
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8636 - loss: 0.2705 - val_accuracy: 0.9412 - val_loss: 0.3463
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9697 - loss: 0.1502 - val_accuracy: 0.8824 - val_loss: 0.5125
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9773 - loss: 0.0732 - val_accuracy: 0.8235 - val_loss: 0.8105
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9924 - loss: 0.0369 - val_accuracy: 0.8235 - val_loss: 0.9589
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9697 - loss: 0.0698 - val_accuracy: 0.9118 - val_loss: 0.8797
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9924 - loss: 0.0326 - val_accuracy: 0.8824 - val_loss: 0.8647
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9924 - loss: 0.0664 - val_accuracy: 0.9118 - val_loss: 0.7877
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9848 - loss: 0.0479 - val_accuracy: 0.8824 - val_loss: 0.8540
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9470 - loss: 0.1637 - val_accuracy: 0.8529 - val_loss: 0.8198
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9773 - loss: 0.0539 - val_accuracy: 0.8529 - val_loss: 0.6790
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9848 - loss: 0.0481 - val_accuracy: 0.8824 - val_loss: 0.7383
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9394 - loss: 0.2690 - val_accuracy: 0.8824 - val_loss: 0.6873
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9773 - loss: 0.1066 - val_accuracy: 0.8529 - val_loss: 0.5917
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9924 - loss: 0.0353 - val_accuracy: 0.8529 - val_loss: 0.5589
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.0221 - val_accuracy: 0.8824 - val_loss: 0.5815
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.9118 - val_loss: 0.6021
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.8824 - val_loss: 0.6908
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8824 - val_loss: 0.7477
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9118 - val_loss: 0.7723
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 7.8237e-04 - val_accuracy: 0.9118 - val_loss: 0.7896
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.7235e-04 - val_accuracy: 0.9118 - val_loss: 0.8032
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 5.8099e-04 - val_accuracy: 0.9118 - val_loss: 0.8142
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 5.2239e-04 - val_accuracy: 0.9118 - val_loss: 0.8235
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 4.6959e-04 - val_accuracy: 0.9118 - val_loss: 0.8326
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 4.2024e-04 - val_accuracy: 0.9118 - val_loss: 0.8405
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.8889e-04 - val_accuracy: 0.9118 - val_loss: 0.8483
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 3.5794e-04 - val_accuracy: 0.9118 - val_loss: 0.8551
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 3.3378e-04 - val_accuracy: 0.9118 - val_loss: 0.8619
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.0873e-04 - val_accuracy: 0.9118 - val_loss: 0.8684
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.8862e-04 - val_accuracy: 0.9118 - val_loss: 0.8743
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 2.7092e-04 - val_accuracy: 0.9118 - val_loss: 0.8805
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 2.5052e-04 - val_accuracy: 0.9118 - val_loss: 0.8858
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3413e-04 - val_accuracy: 0.9118 - val_loss: 0.8927
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.1775e-04 - val_accuracy: 0.9118 - val_loss: 0.8983
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.0380e-04 - val_accuracy: 0.9118 - val_loss: 0.9033
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.9334e-04 - val_accuracy: 0.9118 - val_loss: 0.9080
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.8340e-04 - val_accuracy: 0.9118 - val_loss: 0.9131
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.7272e-04 - val_accuracy: 0.9118 - val_loss: 0.9179
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.6331e-04 - val_accuracy: 0.9118 - val_loss: 0.9239
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.5475e-04 - val_accuracy: 0.9118 - val_loss: 0.9290
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.4684e-04 - val_accuracy: 0.9118 - val_loss: 0.9333
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.4029e-04 - val_accuracy: 0.9118 - val_loss: 0.9373
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.3426e-04 - val_accuracy: 0.9118 - val_loss: 0.9411
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.2914e-04 - val_accuracy: 0.9118 - val_loss: 0.9450
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.2408e-04 - val_accuracy: 0.9118 - val_loss: 0.9489
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.1917e-04 - val_accuracy: 0.9118 - val_loss: 0.9526
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.1437e-04 - val_accuracy: 0.9118 - val_loss: 0.9561
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.1003e-04 - val_accuracy: 0.9118 - val_loss: 0.9597
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 1.0597e-04 - val_accuracy: 0.9118 - val_loss: 0.9630
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.0284e-04 - val_accuracy: 0.9118 - val_loss: 0.9667
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 9.8748e-05 - val_accuracy: 0.9118 - val_loss: 0.9698
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 9.5379e-05 - val_accuracy: 0.9118 - val_loss: 0.9729
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 9.2358e-05 - val_accuracy: 0.9118 - val_loss: 0.9760
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 8.9573e-05 - val_accuracy: 0.9118 - val_loss: 0.9793
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 8.6468e-05 - val_accuracy: 0.9118 - val_loss: 0.9820
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 8.3903e-05 - val_accuracy: 0.9118 - val_loss: 0.9851
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 8.1401e-05 - val_accuracy: 0.9118 - val_loss: 0.9880
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.9002e-05 - val_accuracy: 0.9118 - val_loss: 0.9911
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.6372e-05 - val_accuracy: 0.9118 - val_loss: 0.9938
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.4170e-05 - val_accuracy: 0.9118 - val_loss: 0.9974
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.1803e-05 - val_accuracy: 0.9118 - val_loss: 1.0002
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.0082e-05 - val_accuracy: 0.9118 - val_loss: 1.0030
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.7939e-05 - val_accuracy: 0.9118 - val_loss: 1.0057
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.5996e-05 - val_accuracy: 0.9118 - val_loss: 1.0082
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 6.4113e-05 - val_accuracy: 0.9118 - val_loss: 1.0104
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 6.2589e-05 - val_accuracy: 0.9118 - val_loss: 1.0129
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 6.1002e-05 - val_accuracy: 0.9118 - val_loss: 1.0153
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 5.9618e-05 - val_accuracy: 0.9118 - val_loss: 1.0178
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 5.8060e-05 - val_accuracy: 0.9118 - val_loss: 1.0201
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 5.6616e-05 - val_accuracy: 0.9118 - val_loss: 1.0224
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 5.5206e-05 - val_accuracy: 0.9118 - val_loss: 1.0245
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 5.4061e-05 - val_accuracy: 0.9118 - val_loss: 1.0268
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 5.2790e-05 - val_accuracy: 0.9118 - val_loss: 1.0291
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 5.1506e-05 - val_accuracy: 0.9118 - val_loss: 1.0313
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 5.0282e-05 - val_accuracy: 0.9118 - val_loss: 1.0333
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 4.9251e-05 - val_accuracy: 0.9118 - val_loss: 1.0355
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 4.8265e-05 - val_accuracy: 0.9118 - val_loss: 1.0376
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 4.7046e-05 - val_accuracy: 0.9118 - val_loss: 1.0400
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.5989e-05 - val_accuracy: 0.9118 - val_loss: 1.0421
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 4.4960e-05 - val_accuracy: 0.9118 - val_loss: 1.0441
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.4058e-05 - val_accuracy: 0.9118 - val_loss: 1.0461
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.3137e-05 - val_accuracy: 0.9118 - val_loss: 1.0481
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 4.2159e-05 - val_accuracy: 0.9118 - val_loss: 1.0502
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.1163e-05 - val_accuracy: 0.9118 - val_loss: 1.0525
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.0135e-05 - val_accuracy: 0.9118 - val_loss: 1.0545
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.9237e-05 - val_accuracy: 0.9118 - val_loss: 1.0564
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 3.8323e-05 - val_accuracy: 0.9118 - val_loss: 1.0584
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 3.7562e-05 - val_accuracy: 0.9118 - val_loss: 1.0602
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.6854e-05 - val_accuracy: 0.9118 - val_loss: 1.0620
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.6080e-05 - val_accuracy: 0.9118 - val_loss: 1.0639
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.5450e-05 - val_accuracy: 0.9118 - val_loss: 1.0660
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.4690e-05 - val_accuracy: 0.9118 - val_loss: 1.0680
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.4031e-05 - val_accuracy: 0.9118 - val_loss: 1.0699
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 3.3405e-05 - val_accuracy: 0.9118 - val_loss: 1.0715
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 3.2825e-05 - val_accuracy: 0.9118 - val_loss: 1.0732
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 3.2213e-05 - val_accuracy: 0.9118 - val_loss: 1.0749
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.1567e-05 - val_accuracy: 0.9118 - val_loss: 1.0765
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 3.1021e-05 - val_accuracy: 0.9118 - val_loss: 1.0782

In [31]:
#Predict using Best Model
y_pred_best = best_model.predict(X_test)

y_pred_best = (y_pred_best > 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

In [32]:
#Evaluate Tuned Model
accuracy = accuracy_score(y_test,y_pred_best)

precision = precision_score(y_test,y_pred_best)

recall = recall_score(y_test,y_pred_best)

f1 = f1_score(y_test,y_pred_best)

print("Accuracy :",accuracy)

print("Precision :",precision)

print("Recall :",recall)

print("F1 Score :",f1)

Accuracy : 0.8095238095238095
Precision : 0.875
Recall : 0.7
F1 Score : 0.7777777777777778

In [33]:
#Classification Report
print(classification_report(y_test,y_pred_best))

              precision    recall  f1-score   support

           0       0.77      0.91      0.83        22
           1       0.88      0.70      0.78        20

    accuracy                           0.81        42
   macro avg       0.82      0.80      0.81        42
weighted avg       0.82      0.81      0.81        42

In [34]:
#Compare Default and Tuned Models
results = pd.DataFrame({

    "Model":["Default ANN","Tuned ANN"],

    "Accuracy":[
        accuracy_score(y_test,y_pred),
        accuracy_score(y_test,y_pred_best)
    ],

    "Precision":[
        precision_score(y_test,y_pred),
        precision_score(y_test,y_pred_best)
    ],

    "Recall":[
        recall_score(y_test,y_pred),
        recall_score(y_test,y_pred_best)
    ],

    "F1 Score":[
        f1_score(y_test,y_pred),
        f1_score(y_test,y_pred_best)
    ]

})

print(results)

         Model  Accuracy  Precision  Recall  F1 Score
0  Default ANN  0.857143     0.9375    0.75  0.833333
1    Tuned ANN  0.809524     0.8750    0.70  0.777778